apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend
  - frontend

namespace: study-app
namePrefix: dev-

images:
  - name: ghcr.io/crpruett/study-app-api
    newTag: backend-v0.2.0
  - name: ghcr.io/crpruett/study-app-web:latest
    newTag: frontend-v0.1.0
